root: &root
  ~/repo

restore_cache: &restore_cache
  restore_cache:
    keys:
      - v2-dependencies-{{ checksum "package-lock.json" }}

docker: &docker
  - image: circleci/node:14

attach_workspace: &attach_workspace
  attach_workspace:
    at: *root

version: 2
jobs:
  checkout:
    docker: *docker
    working_directory: *root
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  install:
    docker: *docker
    working_directory: *root
    steps:
      - *attach_workspace
      - *restore_cache
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

  build:
    docker: *docker
    working_directory: *root
    steps:
      - *attach_workspace
      - *restore_cache
      - run: npm run build

  test:
    docker: *docker
    working_directory: *root
    steps:
      - *attach_workspace
      - *restore_cache
      - run: npm run test

  code_quality:
    docker: *docker
    working_directory: *root
    steps:
      - *attach_workspace
      - *restore_cache
      - run: npm run lint

workflows:
  version: 2
  build:
    jobs:
      - checkout
      - install:
          requires:
            - checkout
      - build:
          requires:
            - checkout
            - install
      - test:
          requires:
            - checkout
            - install
      - code_quality:
          requires:
            - checkout
            - install
